<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Logging\**" />
    <EmbeddedResource Remove="Logging\**" />
    <None Remove="Logging\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Data\Local\gateways.json" />
    <None Remove="Data\Local\telemetry.json" />
    <None Remove="Data\Local\users.json" />
	<None Remove="Data\Local\company.json" />
	<None Remove="Data\Local\gateways.json" />

  </ItemGroup>

  <ItemGroup>
    <Content Include="Data\Local\sensors.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

	<ItemGroup>
		<Content Include="Data\Local\company.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	
  <ItemGroup>
    <Content Include="Data\Local\gateways.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\Local\telemetry.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\Local\users.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\Local\SensorLogs\" />
    <Folder Include="Persistence\Json\" />
    <Folder Include="Persistence\LiteDb\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FirebaseAdmin" Version="3.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.3.12" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.11" />
    <PackageReference Include="MongoDB.Driver" Version="3.11.0" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartX.Application\SmartX.Application.csproj" />
    <ProjectReference Include="..\SmartX.Domain\SmartX.Domain.csproj" />
    <ProjectReference Include="..\SmartX.Shared\SmartX.Shared.csproj" />
  </ItemGroup>

</Project>
