<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Contants\**" />
    <Compile Remove="Enums\**" />
    <Compile Remove="Validation\**" />
    <EmbeddedResource Remove="Contants\**" />
    <EmbeddedResource Remove="Enums\**" />
    <EmbeddedResource Remove="Validation\**" />
    <None Remove="Contants\**" />
    <None Remove="Enums\**" />
    <None Remove="Validation\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Bson" Version="3.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartX.Domain\SmartX.Domain.csproj" />
  </ItemGroup>

</Project>
